package com.reservation.paymentservice.exception;

public enum ErrorType {

    FIELD_ERROR, LOGICAL_ERROR, NOT_IMPLEMENTED_ERROR, DATA_INTEGRITY_ERROR, NOT_FOUND_ERROR, SERVER_ERROR, RANGE_ERROR, ACCESS_CONTROL_ERROR

}